import 'dart:convert';
import 'dart:math' as math;

import 'package:flutter/material.dart';
import 'package:google_fonts/google_fonts.dart';
import 'package:intl/intl.dart';
import 'package:timeago/timeago.dart' as timeago;
import 'lat_lng.dart';
import 'place.dart';
import 'uploaded_file.dart';
import '/backend/backend.dart';
import 'package:cloud_firestore/cloud_firestore.dart';
import '/backend/schema/structs/index.dart';
import '/auth/firebase_auth/auth_util.dart';

List<String> getCountrList() {
  final countries = [
    "Afghanistan",
    "Aland Islands",
    "Albania",
    "Algeria",
    "AmericanSamoa",
    "Andorra",
    "Angola",
    "Anguilla",
    "Antarctica",
    "Antigua and Barbuda",
    "Argentina",
    "Armenia",
    "Aruba",
    "Australia",
    "Austria",
    "Azerbaijan",
    "Bahamas",
    "Bahrain",
    "Bangladesh",
    "Barbados",
    "Belarus",
    "Belgium",
    "Belize",
    "Benin",
    "Bermuda",
    "Bhutan",
    "Bolivia",
    "Bosnia and Herzegovina",
    "Botswana",
    "Brazil",
    "British Indian Ocean Territory",
    "Brunei Darussalam",
    "Bulgaria",
    "Burkina Faso",
    "Burundi",
    "Cambodia",
    "Cameroon",
    "Canada",
    "Cape Verde",
    "Cayman Islands",
    "Central African Republic",
    "Chad",
    "Chile",
    "China",
    "Christmas Island",
    "Cocos (Keeling) Islands",
    "Colombia",
    "Comoros",
    "Congo",
    "Congo, The Democratic Republic of the Congo",
    "Cook Islands",
    "Costa Rica",
    "Cote d'Ivoire",
    "Croatia",
    "Cuba",
    "Cyprus",
    "Czech Republic",
    "Denmark",
    "Djibouti",
    "Dominica",
    "Dominican Republic",
    "Ecuador",
    "Egypt",
    "El Salvador",
    "Equatorial Guinea",
    "Eritrea",
    "Estonia",
    "Ethiopia",
    "Falkland Islands (Malvinas",
    "Faroe Islands",
    "Fiji",
    "Finland",
    "France",
    "French Guiana",
    "French Polynesia",
    "Gabon",
    "Gambia",
    "Georgia",
    "Germany",
    "Ghana",
    "Gibraltar",
    "Greece",
    "Greenland",
    "Grenada",
    "Guadeloupe",
    "Guam",
    "Guatemala",
    "Guernsey",
    "Guinea",
    "Guinea-Bissau",
    "Guyana",
    "Haiti",
    "Holy See (Vatican City State",
    "Honduras",
    "Hong Kong",
    "Hungary",
    "Iceland",
    "India",
    "Indonesia",
    "Iran, Islamic Republic of Persian Gulf",
    "Iraq",
    "Ireland",
    "Isle of Man",
    "Israel",
    "Italy",
    "Jamaica",
    "Japan",
    "Jersey",
    "Jordan",
    "Kazakhstan",
    "Kenya",
    "Kiribati",
    "Korea, Democratic People's Republic of Korea",
    "Korea, Republic of South Korea",
    "Kuwait",
    "Kyrgyzstan",
    "Laos",
    "Latvia",
    "Lebanon",
    "Lesotho",
    "Liberia",
    "Libyan Arab Jamahiriya",
    "Liechtenstein",
    "Lithuania",
    "Luxembourg",
    "Macao",
    "Macedonia",
    "Madagascar",
    "Malawi",
    "Malaysia",
    "Maldives",
    "Mali",
    "Malta",
    "Marshall Islands",
    "Martinique",
    "Mauritania",
    "Mauritius",
    "Mayotte",
    "Mexico",
    "Micronesia, Federated States of Micronesia",
    "Moldova",
    "Monaco",
    "Mongolia",
    "Montenegro",
    "Montserrat",
    "Morocco",
    "Mozambique",
    "Myanmar",
    "Namibia",
    "Nauru",
    "Nepal",
    "Netherlands",
    "Netherlands Antilles",
    "New Caledonia",
    "New Zealand",
    "Nicaragua",
    "Niger",
    "Nigeria",
    "Niue",
    "Norfolk Island",
    "Northern Mariana Islands",
    "Norway",
    "Oman",
    "Pakistan",
    "Palau",
    "Palestinian Territory, Occupied",
    "Panama",
    "Papua New Guinea",
    "Paraguay",
    "Peru",
    "Philippines",
    "Pitcairn",
    "Poland",
    "Portugal",
    "Puerto Rico",
    "Qatar",
    "Romania",
    "Russia",
    "Rwanda",
    "Reunion",
    "Saint Barthelemy",
    "Saint Helena, Ascension and Tristan Da Cunha",
    "Saint Kitts and Nevis",
    "Saint Lucia",
    "Saint Martin",
    "Saint Pierre and Miquelon",
    "Saint Vincent and the Grenadines",
    "Samoa",
    "San Marino",
    "Sao Tome and Principe",
    "Saudi Arabia",
    "Senegal",
    "Serbia",
    "Seychelles",
    "Sierra Leone",
    "Singapore",
    "Slovakia",
    "Slovenia",
    "Solomon Islands",
    "Somalia",
    "South Africa",
    "South Sudan",
    "South Georgia and the South Sandwich Islands",
    "Spain",
    "Sri Lanka",
    "Sudan",
    "Suriname",
    "Svalbard and Jan Mayen",
    "Swaziland",
    "Sweden",
    "Switzerland",
    "Syrian Arab Republic",
    "Taiwan",
    "Tajikistan",
    "Tanzania, United Republic of Tanzania",
    "Thailand",
    "Timor-Leste",
    "Togo",
    "Tokelau",
    "Tonga",
    "Trinidad and Tobago",
    "Tunisia",
    "Turkey",
    "Turkmenistan",
    "Turks and Caicos Islands",
    "Tuvalu",
    "Uganda",
    "Ukraine",
    "United Arab Emirates",
    "United Kingdom",
    "United States",
    "Uruguay",
    "Uzbekistan",
    "Vanuatu",
    "Venezuela, Bolivarian Republic of Venezuela",
    "Vietnam",
    "Virgin Islands, British",
    "Virgin Islands, U.S",
    "Wallis and Futuna",
    "Yemen",
    "Zambia",
    "Zimbabwe",
  ];

  return countries;
}

String? getDailCode(String? countryName) {
  if (countryName == null) {
    return null;
  }
  final countryInfoJson = {
    "Afghanistan": {"dial_code": "93", "code": "AF"},
    "Aland Islands": {"dial_code": "358", "code": "AX"},
    "Albania": {"dial_code": "355", "code": "AL"},
    "Algeria": {"dial_code": "213", "code": "DZ"},
    "AmericanSamoa": {"dial_code": "1684", "code": "AS"},
    "Andorra": {"dial_code": "376", "code": "AD"},
    "Angola": {"dial_code": "244", "code": "AO"},
    "Anguilla": {"dial_code": "1264", "code": "AI"},
    "Antarctica": {"dial_code": "672", "code": "AQ"},
    "Antigua and Barbuda": {"dial_code": "1268", "code": "AG"},
    "Argentina": {"dial_code": "54", "code": "AR"},
    "Armenia": {"dial_code": "374", "code": "AM"},
    "Aruba": {"dial_code": "297", "code": "AW"},
    "Australia": {"dial_code": "61", "code": "AU"},
    "Austria": {"dial_code": "43", "code": "AT"},
    "Azerbaijan": {"dial_code": "994", "code": "AZ"},
    "Bahamas": {"dial_code": "1242", "code": "BS"},
    "Bahrain": {"dial_code": "973", "code": "BH"},
    "Bangladesh": {"dial_code": "880", "code": "BD"},
    "Barbados": {"dial_code": "1246", "code": "BB"},
    "Belarus": {"dial_code": "375", "code": "BY"},
    "Belgium": {"dial_code": "32", "code": "BE"},
    "Belize": {"dial_code": "501", "code": "BZ"},
    "Benin": {"dial_code": "229", "code": "BJ"},
    "Bermuda": {"dial_code": "1441", "code": "BM"},
    "Bhutan": {"dial_code": "975", "code": "BT"},
    "Bolivia, Plurinational State of": {"dial_code": "591", "code": "BO"},
    "Bosnia and Herzegovina": {"dial_code": "387", "code": "BA"},
    "Botswana": {"dial_code": "267", "code": "BW"},
    "Brazil": {"dial_code": "55", "code": "BR"},
    "British Indian Ocean Territory": {"dial_code": "246", "code": "IO"},
    "Brunei Darussalam": {"dial_code": "673", "code": "BN"},
    "Bulgaria": {"dial_code": "359", "code": "BG"},
    "Burkina Faso": {"dial_code": "226", "code": "BF"},
    "Burundi": {"dial_code": "257", "code": "BI"},
    "Cambodia": {"dial_code": "855", "code": "KH"},
    "Cameroon": {"dial_code": "237", "code": "CM"},
    "Canada": {"dial_code": "1", "code": "CA"},
    "Cape Verde": {"dial_code": "238", "code": "CV"},
    "Cayman Islands": {"dial_code": " 345", "code": "KY"},
    "Central African Republic": {"dial_code": "236", "code": "CF"},
    "Chad": {"dial_code": "235", "code": "TD"},
    "Chile": {"dial_code": "56", "code": "CL"},
    "China": {"dial_code": "86", "code": "CN"},
    "Christmas Island": {"dial_code": "61", "code": "CX"},
    "Cocos (Keeling) Islands": {"dial_code": "61", "code": "CC"},
    "Colombia": {"dial_code": "57", "code": "CO"},
    "Comoros": {"dial_code": "269", "code": "KM"},
    "Congo": {"dial_code": "242", "code": "CG"},
    "Congo, The Democratic Republic of the Congo": {
      "dial_code": "243",
      "code": "CD"
    },
    "Cook Islands": {"dial_code": "682", "code": "CK"},
    "Costa Rica": {"dial_code": "506", "code": "CR"},
    "Cote d'Ivoire": {"dial_code": "225", "code": "CI"},
    "Croatia": {"dial_code": "385", "code": "HR"},
    "Cuba": {"dial_code": "53", "code": "CU"},
    "Cyprus": {"dial_code": "357", "code": "CY"},
    "Czech Republic": {"dial_code": "420", "code": "CZ"},
    "Denmark": {"dial_code": "45", "code": "DK"},
    "Djibouti": {"dial_code": "253", "code": "DJ"},
    "Dominica": {"dial_code": "1767", "code": "DM"},
    "Dominican Republic": {"dial_code": "1849", "code": "DO"},
    "Ecuador": {"dial_code": "593", "code": "EC"},
    "Egypt": {"dial_code": "20", "code": "EG"},
    "El Salvador": {"dial_code": "503", "code": "SV"},
    "Equatorial Guinea": {"dial_code": "240", "code": "GQ"},
    "Eritrea": {"dial_code": "291", "code": "ER"},
    "Estonia": {"dial_code": "372", "code": "EE"},
    "Ethiopia": {"dial_code": "251", "code": "ET"},
    "Falkland Islands (Malvinas)": {"dial_code": "500", "code": "FK"},
    "Faroe Islands": {"dial_code": "298", "code": "FO"},
    "Fiji": {"dial_code": "679", "code": "FJ"},
    "Finland": {"dial_code": "358", "code": "FI"},
    "France": {"dial_code": "33", "code": "FR"},
    "French Guiana": {"dial_code": "594", "code": "GF"},
    "French Polynesia": {"dial_code": "689", "code": "PF"},
    "Gabon": {"dial_code": "241", "code": "GA"},
    "Gambia": {"dial_code": "220", "code": "GM"},
    "Georgia": {"dial_code": "995", "code": "GE"},
    "Germany": {"dial_code": "49", "code": "DE"},
    "Ghana": {"dial_code": "233", "code": "GH"},
    "Gibraltar": {"dial_code": "350", "code": "GI"},
    "Greece": {"dial_code": "30", "code": "GR"},
    "Greenland": {"dial_code": "299", "code": "GL"},
    "Grenada": {"dial_code": "1473", "code": "GD"},
    "Guadeloupe": {"dial_code": "590", "code": "GP"},
    "Guam": {"dial_code": "1671", "code": "GU"},
    "Guatemala": {"dial_code": "502", "code": "GT"},
    "Guernsey": {"dial_code": "44", "code": "GG"},
    "Guinea": {"dial_code": "224", "code": "GN"},
    "Guinea-Bissau": {"dial_code": "245", "code": "GW"},
    "Guyana": {"dial_code": "595", "code": "GY"},
    "Haiti": {"dial_code": "509", "code": "HT"},
    "Holy See (Vatican City State)": {"dial_code": "379", "code": "VA"},
    "Honduras": {"dial_code": "504", "code": "HN"},
    "Hong Kong": {"dial_code": "852", "code": "HK"},
    "Hungary": {"dial_code": "36", "code": "HU"},
    "Iceland": {"dial_code": "354", "code": "IS"},
    "India": {"dial_code": "91", "code": "IN"},
    "Indonesia": {"dial_code": "62", "code": "ID"},
    "Iran, Islamic Republic of Persian Gulf": {"dial_code": "98", "code": "IR"},
    "Iraq": {"dial_code": "964", "code": "IQ"},
    "Ireland": {"dial_code": "353", "code": "IE"},
    "Isle of Man": {"dial_code": "44", "code": "IM"},
    "Israel": {"dial_code": "972", "code": "IL"},
    "Italy": {"dial_code": "39", "code": "IT"},
    "Jamaica": {"dial_code": "1876", "code": "JM"},
    "Japan": {"dial_code": "81", "code": "JP"},
    "Jersey": {"dial_code": "44", "code": "JE"},
    "Jordan": {"dial_code": "962", "code": "JO"},
    "Kazakhstan": {"dial_code": "77", "code": "KZ"},
    "Kenya": {"dial_code": "254", "code": "KE"},
    "Kiribati": {"dial_code": "686", "code": "KI"},
    "Korea, Democratic People's Republic of Korea": {
      "dial_code": "850",
      "code": "KP"
    },
    "Korea, Republic of South Korea": {"dial_code": "82", "code": "KR"},
    "Kuwait": {"dial_code": "965", "code": "KW"},
    "Kyrgyzstan": {"dial_code": "996", "code": "KG"},
    "Laos": {"dial_code": "856", "code": "LA"},
    "Latvia": {"dial_code": "371", "code": "LV"},
    "Lebanon": {"dial_code": "961", "code": "LB"},
    "Lesotho": {"dial_code": "266", "code": "LS"},
    "Liberia": {"dial_code": "231", "code": "LR"},
    "Libyan Arab Jamahiriya": {"dial_code": "218", "code": "LY"},
    "Liechtenstein": {"dial_code": "423", "code": "LI"},
    "Lithuania": {"dial_code": "370", "code": "LT"},
    "Luxembourg": {"dial_code": "352", "code": "LU"},
    "Macao": {"dial_code": "853", "code": "MO"},
    "Macedonia": {"dial_code": "389", "code": "MK"},
    "Madagascar": {"dial_code": "261", "code": "MG"},
    "Malawi": {"dial_code": "265", "code": "MW"},
    "Malaysia": {"dial_code": "60", "code": "MY"},
    "Maldives": {"dial_code": "960", "code": "MV"},
    "Mali": {"dial_code": "223", "code": "ML"},
    "Malta": {"dial_code": "356", "code": "MT"},
    "Marshall Islands": {"dial_code": "692", "code": "MH"},
    "Martinique": {"dial_code": "596", "code": "MQ"},
    "Mauritania": {"dial_code": "222", "code": "MR"},
    "Mauritius": {"dial_code": "230", "code": "MU"},
    "Mayotte": {"dial_code": "262", "code": "YT"},
    "Mexico": {"dial_code": "52", "code": "MX"},
    "Micronesia, Federated States of Micronesia": {
      "dial_code": "691",
      "code": "FM"
    },
    "Moldova": {"dial_code": "373", "code": "MD"},
    "Monaco": {"dial_code": "377", "code": "MC"},
    "Mongolia": {"dial_code": "976", "code": "MN"},
    "Montenegro": {"dial_code": "382", "code": "ME"},
    "Montserrat": {"dial_code": "1664", "code": "MS"},
    "Morocco": {"dial_code": "212", "code": "MA"},
    "Mozambique": {"dial_code": "258", "code": "MZ"},
    "Myanmar": {"dial_code": "95", "code": "MM"},
    "Namibia": {"dial_code": "264", "code": "NA"},
    "Nauru": {"dial_code": "674", "code": "NR"},
    "Nepal": {"dial_code": "977", "code": "NP"},
    "Netherlands": {"dial_code": "31", "code": "NL"},
    "Netherlands Antilles": {"dial_code": "599", "code": "AN"},
    "New Caledonia": {"dial_code": "687", "code": "NC"},
    "New Zealand": {"dial_code": "64", "code": "NZ"},
    "Nicaragua": {"dial_code": "505", "code": "NI"},
    "Niger": {"dial_code": "227", "code": "NE"},
    "Nigeria": {"dial_code": "234", "code": "NG"},
    "Niue": {"dial_code": "683", "code": "NU"},
    "Norfolk Island": {"dial_code": "672", "code": "NF"},
    "Northern Mariana Islands": {"dial_code": "1670", "code": "MP"},
    "Norway": {"dial_code": "47", "code": "NO"},
    "Oman": {"dial_code": "968", "code": "OM"},
    "Pakistan": {"dial_code": "92", "code": "PK"},
    "Palau": {"dial_code": "680", "code": "PW"},
    "Palestinian Territory, Occupied": {"dial_code": "970", "code": "PS"},
    "Panama": {"dial_code": "507", "code": "PA"},
    "Papua New Guinea": {"dial_code": "675", "code": "PG"},
    "Paraguay": {"dial_code": "595", "code": "PY"},
    "Peru": {"dial_code": "51", "code": "PE"},
    "Philippines": {"dial_code": "63", "code": "PH"},
    "Pitcairn": {"dial_code": "872", "code": "PN"},
    "Poland": {"dial_code": "48", "code": "PL"},
    "Portugal": {"dial_code": "351", "code": "PT"},
    "Puerto Rico": {"dial_code": "1939", "code": "PR"},
    "Qatar": {"dial_code": "974", "code": "QA"},
    "Romania": {"dial_code": "40", "code": "RO"},
    "Russia": {"dial_code": "7", "code": "RU"},
    "Rwanda": {"dial_code": "250", "code": "RW"},
    "Reunion": {"dial_code": "262", "code": "RE"},
    "Saint Barthelemy": {"dial_code": "590", "code": "BL"},
    "Saint Helena, Ascension and Tristan Da Cunha": {
      "dial_code": "290",
      "code": "SH"
    },
    "Saint Kitts and Nevis": {"dial_code": "1869", "code": "KN"},
    "Saint Lucia": {"dial_code": "1758", "code": "LC"},
    "Saint Martin": {"dial_code": "590", "code": "MF"},
    "Saint Pierre and Miquelon": {"dial_code": "508", "code": "PM"},
    "Saint Vincent and the Grenadines": {"dial_code": "1784", "code": "VC"},
    "Samoa": {"dial_code": "685", "code": "WS"},
    "San Marino": {"dial_code": "378", "code": "SM"},
    "Sao Tome and Principe": {"dial_code": "239", "code": "ST"},
    "Saudi Arabia": {"dial_code": "966", "code": "SA"},
    "Senegal": {"dial_code": "221", "code": "SN"},
    "Serbia": {"dial_code": "381", "code": "RS"},
    "Seychelles": {"dial_code": "248", "code": "SC"},
    "Sierra Leone": {"dial_code": "232", "code": "SL"},
    "Singapore": {"dial_code": "65", "code": "SG"},
    "Slovakia": {"dial_code": "421", "code": "SK"},
    "Slovenia": {"dial_code": "386", "code": "SI"},
    "Solomon Islands": {"dial_code": "677", "code": "SB"},
    "Somalia": {"dial_code": "252", "code": "SO"},
    "South Africa": {"dial_code": "27", "code": "ZA"},
    "South Sudan": {"dial_code": "211", "code": "SS"},
    "South Georgia and the South Sandwich Islands": {
      "dial_code": "500",
      "code": "GS"
    },
    "Spain": {"dial_code": "34", "code": "ES"},
    "Sri Lanka": {"dial_code": "94", "code": "LK"},
    "Sudan": {"dial_code": "249", "code": "SD"},
    "Suriname": {"dial_code": "597", "code": "SR"},
    "Svalbard and Jan Mayen": {"dial_code": "47", "code": "SJ"},
    "Swaziland": {"dial_code": "268", "code": "SZ"},
    "Sweden": {"dial_code": "46", "code": "SE"},
    "Switzerland": {"dial_code": "41", "code": "CH"},
    "Syrian Arab Republic": {"dial_code": "963", "code": "SY"},
    "Taiwan": {"dial_code": "886", "code": "TW"},
    "Tajikistan": {"dial_code": "992", "code": "TJ"},
    "Tanzania, United Republic of Tanzania": {"dial_code": "255", "code": "TZ"},
    "Thailand": {"dial_code": "66", "code": "TH"},
    "Timor-Leste": {"dial_code": "670", "code": "TL"},
    "Togo": {"dial_code": "228", "code": "TG"},
    "Tokelau": {"dial_code": "690", "code": "TK"},
    "Tonga": {"dial_code": "676", "code": "TO"},
    "Trinidad and Tobago": {"dial_code": "1868", "code": "TT"},
    "Tunisia": {"dial_code": "216", "code": "TN"},
    "Turkey": {"dial_code": "90", "code": "TR"},
    "Turkmenistan": {"dial_code": "993", "code": "TM"},
    "Turks and Caicos Islands": {"dial_code": "1649", "code": "TC"},
    "Tuvalu": {"dial_code": "688", "code": "TV"},
    "Uganda": {"dial_code": "256", "code": "UG"},
    "Ukraine": {"dial_code": "380", "code": "UA"},
    "United Arab Emirates": {"dial_code": "971", "code": "AE"},
    "United Kingdom": {"dial_code": "44", "code": "GB"},
    "United States": {"dial_code": "1", "code": "US"},
    "Uruguay": {"dial_code": "598", "code": "UY"},
    "Uzbekistan": {"dial_code": "998", "code": "UZ"},
    "Vanuatu": {"dial_code": "678", "code": "VU"},
    "Venezuela, Bolivarian Republic of Venezuela": {
      "dial_code": "58",
      "code": "VE"
    },
    "Vietnam": {"dial_code": "84", "code": "VN"},
    "Virgin Islands, British": {"dial_code": "1284", "code": "VG"},
    "Virgin Islands, U.S.": {"dial_code": "1340", "code": "VI"},
    "Wallis and Futuna": {"dial_code": "681", "code": "WF"},
    "Yemen": {"dial_code": "967", "code": "YE"},
    "Zambia": {"dial_code": "260", "code": "ZM"},
    "Zimbabwe": {"dial_code": "263", "code": "ZW"}
  };

  final countryDialCode = countryInfoJson[countryName]?["dial_code"];

  if (countryDialCode != null) {
    return countryDialCode;
  }

  return null;
}

String? getCountryFlag(String? countryName) {
  if (countryName == null) {
    return null;
  }
  final countryInfoJson = {
    "Afghanistan": {"dial_code": "+93", "code": "AF"},
    "Aland Islands": {"dial_code": "+358", "code": "AX"},
    "Albania": {"dial_code": "+355", "code": "AL"},
    "Algeria": {"dial_code": "+213", "code": "DZ"},
    "AmericanSamoa": {"dial_code": "+1684", "code": "AS"},
    "Andorra": {"dial_code": "+376", "code": "AD"},
    "Angola": {"dial_code": "+244", "code": "AO"},
    "Anguilla": {"dial_code": "+1264", "code": "AI"},
    "Antarctica": {"dial_code": "+672", "code": "AQ"},
    "Antigua and Barbuda": {"dial_code": "+1268", "code": "AG"},
    "Argentina": {"dial_code": "+54", "code": "AR"},
    "Armenia": {"dial_code": "+374", "code": "AM"},
    "Aruba": {"dial_code": "+297", "code": "AW"},
    "Australia": {"dial_code": "+61", "code": "AU"},
    "Austria": {"dial_code": "+43", "code": "AT"},
    "Azerbaijan": {"dial_code": "+994", "code": "AZ"},
    "Bahamas": {"dial_code": "+1242", "code": "BS"},
    "Bahrain": {"dial_code": "+973", "code": "BH"},
    "Bangladesh": {"dial_code": "+880", "code": "BD"},
    "Barbados": {"dial_code": "+1246", "code": "BB"},
    "Belarus": {"dial_code": "+375", "code": "BY"},
    "Belgium": {"dial_code": "+32", "code": "BE"},
    "Belize": {"dial_code": "+501", "code": "BZ"},
    "Benin": {"dial_code": "+229", "code": "BJ"},
    "Bermuda": {"dial_code": "+1441", "code": "BM"},
    "Bhutan": {"dial_code": "+975", "code": "BT"},
    "Bolivia, Plurinational State of": {"dial_code": "+591", "code": "BO"},
    "Bosnia and Herzegovina": {"dial_code": "+387", "code": "BA"},
    "Botswana": {"dial_code": "+267", "code": "BW"},
    "Brazil": {"dial_code": "+55", "code": "BR"},
    "British Indian Ocean Territory": {"dial_code": "+246", "code": "IO"},
    "Brunei Darussalam": {"dial_code": "+673", "code": "BN"},
    "Bulgaria": {"dial_code": "+359", "code": "BG"},
    "Burkina Faso": {"dial_code": "+226", "code": "BF"},
    "Burundi": {"dial_code": "+257", "code": "BI"},
    "Cambodia": {"dial_code": "+855", "code": "KH"},
    "Cameroon": {"dial_code": "+237", "code": "CM"},
    "Canada": {"dial_code": "+1", "code": "CA"},
    "Cape Verde": {"dial_code": "+238", "code": "CV"},
    "Cayman Islands": {"dial_code": "+ 345", "code": "KY"},
    "Central African Republic": {"dial_code": "+236", "code": "CF"},
    "Chad": {"dial_code": "+235", "code": "TD"},
    "Chile": {"dial_code": "+56", "code": "CL"},
    "China": {"dial_code": "+86", "code": "CN"},
    "Christmas Island": {"dial_code": "+61", "code": "CX"},
    "Cocos (Keeling) Islands": {"dial_code": "+61", "code": "CC"},
    "Colombia": {"dial_code": "+57", "code": "CO"},
    "Comoros": {"dial_code": "+269", "code": "KM"},
    "Congo": {"dial_code": "+242", "code": "CG"},
    "Congo, The Democratic Republic of the Congo": {
      "dial_code": "+243",
      "code": "CD"
    },
    "Cook Islands": {"dial_code": "+682", "code": "CK"},
    "Costa Rica": {"dial_code": "+506", "code": "CR"},
    "Cote d'Ivoire": {"dial_code": "+225", "code": "CI"},
    "Croatia": {"dial_code": "+385", "code": "HR"},
    "Cuba": {"dial_code": "+53", "code": "CU"},
    "Cyprus": {"dial_code": "+357", "code": "CY"},
    "Czech Republic": {"dial_code": "+420", "code": "CZ"},
    "Denmark": {"dial_code": "+45", "code": "DK"},
    "Djibouti": {"dial_code": "+253", "code": "DJ"},
    "Dominica": {"dial_code": "+1767", "code": "DM"},
    "Dominican Republic": {"dial_code": "+1849", "code": "DO"},
    "Ecuador": {"dial_code": "+593", "code": "EC"},
    "Egypt": {"dial_code": "+20", "code": "EG"},
    "El Salvador": {"dial_code": "+503", "code": "SV"},
    "Equatorial Guinea": {"dial_code": "+240", "code": "GQ"},
    "Eritrea": {"dial_code": "+291", "code": "ER"},
    "Estonia": {"dial_code": "+372", "code": "EE"},
    "Ethiopia": {"dial_code": "+251", "code": "ET"},
    "Falkland Islands (Malvinas)": {"dial_code": "+500", "code": "FK"},
    "Faroe Islands": {"dial_code": "+298", "code": "FO"},
    "Fiji": {"dial_code": "+679", "code": "FJ"},
    "Finland": {"dial_code": "+358", "code": "FI"},
    "France": {"dial_code": "+33", "code": "FR"},
    "French Guiana": {"dial_code": "+594", "code": "GF"},
    "French Polynesia": {"dial_code": "+689", "code": "PF"},
    "Gabon": {"dial_code": "+241", "code": "GA"},
    "Gambia": {"dial_code": "+220", "code": "GM"},
    "Georgia": {"dial_code": "+995", "code": "GE"},
    "Germany": {"dial_code": "+49", "code": "DE"},
    "Ghana": {"dial_code": "+233", "code": "GH"},
    "Gibraltar": {"dial_code": "+350", "code": "GI"},
    "Greece": {"dial_code": "+30", "code": "GR"},
    "Greenland": {"dial_code": "+299", "code": "GL"},
    "Grenada": {"dial_code": "+1473", "code": "GD"},
    "Guadeloupe": {"dial_code": "+590", "code": "GP"},
    "Guam": {"dial_code": "+1671", "code": "GU"},
    "Guatemala": {"dial_code": "+502", "code": "GT"},
    "Guernsey": {"dial_code": "+44", "code": "GG"},
    "Guinea": {"dial_code": "+224", "code": "GN"},
    "Guinea-Bissau": {"dial_code": "+245", "code": "GW"},
    "Guyana": {"dial_code": "+595", "code": "GY"},
    "Haiti": {"dial_code": "+509", "code": "HT"},
    "Holy See (Vatican City State)": {"dial_code": "+379", "code": "VA"},
    "Honduras": {"dial_code": "+504", "code": "HN"},
    "Hong Kong": {"dial_code": "+852", "code": "HK"},
    "Hungary": {"dial_code": "+36", "code": "HU"},
    "Iceland": {"dial_code": "+354", "code": "IS"},
    "India": {"dial_code": "+91", "code": "IN"},
    "Indonesia": {"dial_code": "+62", "code": "ID"},
    "Iran, Islamic Republic of Persian Gulf": {
      "dial_code": "+98",
      "code": "IR"
    },
    "Iraq": {"dial_code": "+964", "code": "IQ"},
    "Ireland": {"dial_code": "+353", "code": "IE"},
    "Isle of Man": {"dial_code": "+44", "code": "IM"},
    "Israel": {"dial_code": "+972", "code": "IL"},
    "Italy": {"dial_code": "+39", "code": "IT"},
    "Jamaica": {"dial_code": "+1876", "code": "JM"},
    "Japan": {"dial_code": "+81", "code": "JP"},
    "Jersey": {"dial_code": "+44", "code": "JE"},
    "Jordan": {"dial_code": "+962", "code": "JO"},
    "Kazakhstan": {"dial_code": "+77", "code": "KZ"},
    "Kenya": {"dial_code": "+254", "code": "KE"},
    "Kiribati": {"dial_code": "+686", "code": "KI"},
    "Korea, Democratic People's Republic of Korea": {
      "dial_code": "+850",
      "code": "KP"
    },
    "Korea, Republic of South Korea": {"dial_code": "+82", "code": "KR"},
    "Kuwait": {"dial_code": "+965", "code": "KW"},
    "Kyrgyzstan": {"dial_code": "+996", "code": "KG"},
    "Laos": {"dial_code": "+856", "code": "LA"},
    "Latvia": {"dial_code": "+371", "code": "LV"},
    "Lebanon": {"dial_code": "+961", "code": "LB"},
    "Lesotho": {"dial_code": "+266", "code": "LS"},
    "Liberia": {"dial_code": "+231", "code": "LR"},
    "Libyan Arab Jamahiriya": {"dial_code": "+218", "code": "LY"},
    "Liechtenstein": {"dial_code": "+423", "code": "LI"},
    "Lithuania": {"dial_code": "+370", "code": "LT"},
    "Luxembourg": {"dial_code": "+352", "code": "LU"},
    "Macao": {"dial_code": "+853", "code": "MO"},
    "Macedonia": {"dial_code": "+389", "code": "MK"},
    "Madagascar": {"dial_code": "+261", "code": "MG"},
    "Malawi": {"dial_code": "+265", "code": "MW"},
    "Malaysia": {"dial_code": "+60", "code": "MY"},
    "Maldives": {"dial_code": "+960", "code": "MV"},
    "Mali": {"dial_code": "+223", "code": "ML"},
    "Malta": {"dial_code": "+356", "code": "MT"},
    "Marshall Islands": {"dial_code": "+692", "code": "MH"},
    "Martinique": {"dial_code": "+596", "code": "MQ"},
    "Mauritania": {"dial_code": "+222", "code": "MR"},
    "Mauritius": {"dial_code": "+230", "code": "MU"},
    "Mayotte": {"dial_code": "+262", "code": "YT"},
    "Mexico": {"dial_code": "+52", "code": "MX"},
    "Micronesia, Federated States of Micronesia": {
      "dial_code": "+691",
      "code": "FM"
    },
    "Moldova": {"dial_code": "+373", "code": "MD"},
    "Monaco": {"dial_code": "+377", "code": "MC"},
    "Mongolia": {"dial_code": "+976", "code": "MN"},
    "Montenegro": {"dial_code": "+382", "code": "ME"},
    "Montserrat": {"dial_code": "+1664", "code": "MS"},
    "Morocco": {"dial_code": "+212", "code": "MA"},
    "Mozambique": {"dial_code": "+258", "code": "MZ"},
    "Myanmar": {"dial_code": "+95", "code": "MM"},
    "Namibia": {"dial_code": "+264", "code": "NA"},
    "Nauru": {"dial_code": "+674", "code": "NR"},
    "Nepal": {"dial_code": "+977", "code": "NP"},
    "Netherlands": {"dial_code": "+31", "code": "NL"},
    "Netherlands Antilles": {"dial_code": "+599", "code": "AN"},
    "New Caledonia": {"dial_code": "+687", "code": "NC"},
    "New Zealand": {"dial_code": "+64", "code": "NZ"},
    "Nicaragua": {"dial_code": "+505", "code": "NI"},
    "Niger": {"dial_code": "+227", "code": "NE"},
    "Nigeria": {"dial_code": "+234", "code": "NG"},
    "Niue": {"dial_code": "+683", "code": "NU"},
    "Norfolk Island": {"dial_code": "+672", "code": "NF"},
    "Northern Mariana Islands": {"dial_code": "+1670", "code": "MP"},
    "Norway": {"dial_code": "+47", "code": "NO"},
    "Oman": {"dial_code": "+968", "code": "OM"},
    "Pakistan": {"dial_code": "+92", "code": "PK"},
    "Palau": {"dial_code": "+680", "code": "PW"},
    "Palestinian Territory, Occupied": {"dial_code": "+970", "code": "PS"},
    "Panama": {"dial_code": "+507", "code": "PA"},
    "Papua New Guinea": {"dial_code": "+675", "code": "PG"},
    "Paraguay": {"dial_code": "+595", "code": "PY"},
    "Peru": {"dial_code": "+51", "code": "PE"},
    "Philippines": {"dial_code": "+63", "code": "PH"},
    "Pitcairn": {"dial_code": "+872", "code": "PN"},
    "Poland": {"dial_code": "+48", "code": "PL"},
    "Portugal": {"dial_code": "+351", "code": "PT"},
    "Puerto Rico": {"dial_code": "+1939", "code": "PR"},
    "Qatar": {"dial_code": "+974", "code": "QA"},
    "Romania": {"dial_code": "+40", "code": "RO"},
    "Russia": {"dial_code": "+7", "code": "RU"},
    "Rwanda": {"dial_code": "+250", "code": "RW"},
    "Reunion": {"dial_code": "+262", "code": "RE"},
    "Saint Barthelemy": {"dial_code": "+590", "code": "BL"},
    "Saint Helena, Ascension and Tristan Da Cunha": {
      "dial_code": "+290",
      "code": "SH"
    },
    "Saint Kitts and Nevis": {"dial_code": "+1869", "code": "KN"},
    "Saint Lucia": {"dial_code": "+1758", "code": "LC"},
    "Saint Martin": {"dial_code": "+590", "code": "MF"},
    "Saint Pierre and Miquelon": {"dial_code": "+508", "code": "PM"},
    "Saint Vincent and the Grenadines": {"dial_code": "+1784", "code": "VC"},
    "Samoa": {"dial_code": "+685", "code": "WS"},
    "San Marino": {"dial_code": "+378", "code": "SM"},
    "Sao Tome and Principe": {"dial_code": "+239", "code": "ST"},
    "Saudi Arabia": {"dial_code": "+966", "code": "SA"},
    "Senegal": {"dial_code": "+221", "code": "SN"},
    "Serbia": {"dial_code": "+381", "code": "RS"},
    "Seychelles": {"dial_code": "+248", "code": "SC"},
    "Sierra Leone": {"dial_code": "+232", "code": "SL"},
    "Singapore": {"dial_code": "+65", "code": "SG"},
    "Slovakia": {"dial_code": "+421", "code": "SK"},
    "Slovenia": {"dial_code": "+386", "code": "SI"},
    "Solomon Islands": {"dial_code": "+677", "code": "SB"},
    "Somalia": {"dial_code": "+252", "code": "SO"},
    "South Africa": {"dial_code": "+27", "code": "ZA"},
    "South Sudan": {"dial_code": "+211", "code": "SS"},
    "South Georgia and the South Sandwich Islands": {
      "dial_code": "+500",
      "code": "GS"
    },
    "Spain": {"dial_code": "+34", "code": "ES"},
    "Sri Lanka": {"dial_code": "+94", "code": "LK"},
    "Sudan": {"dial_code": "+249", "code": "SD"},
    "Suriname": {"dial_code": "+597", "code": "SR"},
    "Svalbard and Jan Mayen": {"dial_code": "+47", "code": "SJ"},
    "Swaziland": {"dial_code": "+268", "code": "SZ"},
    "Sweden": {"dial_code": "+46", "code": "SE"},
    "Switzerland": {"dial_code": "+41", "code": "CH"},
    "Syrian Arab Republic": {"dial_code": "+963", "code": "SY"},
    "Taiwan": {"dial_code": "+886", "code": "TW"},
    "Tajikistan": {"dial_code": "+992", "code": "TJ"},
    "Tanzania, United Republic of Tanzania": {
      "dial_code": "+255",
      "code": "TZ"
    },
    "Thailand": {"dial_code": "+66", "code": "TH"},
    "Timor-Leste": {"dial_code": "+670", "code": "TL"},
    "Togo": {"dial_code": "+228", "code": "TG"},
    "Tokelau": {"dial_code": "+690", "code": "TK"},
    "Tonga": {"dial_code": "+676", "code": "TO"},
    "Trinidad and Tobago": {"dial_code": "+1868", "code": "TT"},
    "Tunisia": {"dial_code": "+216", "code": "TN"},
    "Turkey": {"dial_code": "+90", "code": "TR"},
    "Turkmenistan": {"dial_code": "+993", "code": "TM"},
    "Turks and Caicos Islands": {"dial_code": "+1649", "code": "TC"},
    "Tuvalu": {"dial_code": "+688", "code": "TV"},
    "Uganda": {"dial_code": "+256", "code": "UG"},
    "Ukraine": {"dial_code": "+380", "code": "UA"},
    "United Arab Emirates": {"dial_code": "+971", "code": "AE"},
    "United Kingdom": {"dial_code": "+44", "code": "GB"},
    "United States": {"dial_code": "+1", "code": "US"},
    "Uruguay": {"dial_code": "+598", "code": "UY"},
    "Uzbekistan": {"dial_code": "+998", "code": "UZ"},
    "Vanuatu": {"dial_code": "+678", "code": "VU"},
    "Venezuela, Bolivarian Republic of Venezuela": {
      "dial_code": "+58",
      "code": "VE"
    },
    "Vietnam": {"dial_code": "+84", "code": "VN"},
    "Virgin Islands, British": {"dial_code": "+1284", "code": "VG"},
    "Virgin Islands, U.S.": {"dial_code": "+1340", "code": "VI"},
    "Wallis and Futuna": {"dial_code": "+681", "code": "WF"},
    "Yemen": {"dial_code": "+967", "code": "YE"},
    "Zambia": {"dial_code": "+260", "code": "ZM"},
    "Zimbabwe": {"dial_code": "+263", "code": "ZW"}
  };

  final countryCode = countryInfoJson[countryName]?["code"];

  if (countryCode != null) {
    final countryCodeInLowerCase = countryCode.toLowerCase();
    return 'https://flagcdn.com/h80/$countryCodeInLowerCase.png';
  }

  return null;
}

int? getPhoneLength(String? countryName) {
  if (countryName == null) {
    return null;
  }
  final countryInfoJson = {
    "Afghanistan": {"phone_length": "9"},
    "Albania": {"phone_length": "8-9"},
    "Algeria": {"phone_length": "9"},
    "Andorra": {"phone_length": "6"},
    "Angola": {"phone_length": "9"},
    "Argentina": {"phone_length": "10"},
    "Armenia": {"phone_length": "8"},
    "Australia": {"phone_length": "9"},
    "Austria": {"phone_length": "10"},
    "Azerbaijan": {"phone_length": "9"},
    "Bahrain": {"phone_length": "8"},
    "Bangladesh": {"phone_length": "10"},
    "Belarus": {"phone_length": "9"},
    "Belgium": {"phone_length": "8-9"},
    "Belize": {"phone_length": "7"},
    "Benin": {"phone_length": "8"},
    "Bhutan": {"phone_length": "7-8"},
    "Bolivia": {"phone_length": "8"},
    "Bosnia and Herzegovina": {"phone_length": "8"},
    "Botswana": {"phone_length": "7-8"},
    "Brazil": {"phone_length": "10-11"},
    "Bulgaria": {"phone_length": "7-9"},
    "Burkina Faso": {"phone_length": "8"},
    "Burundi": {"phone_length": "8"},
    "Cambodia": {"phone_length": "8-9"},
    "Cameroon": {"phone_length": "8"},
    "Canada": {"phone_length": "10"},
    "Chile": {"phone_length": "9"},
    "China": {"phone_length": "11"},
    "Colombia": {"phone_length": "10"},
    "Cuba": {"phone_length": "8"},
    "Denmark": {"phone_length": "8"},
    "Egypt": {"phone_length": "10"},
    "France": {"phone_length": "9"},
    "Germany": {"phone_length": "10-11"},
    "Greece": {"phone_length": "10"},
    "India": {"phone_length": "10"},
    "Indonesia": {"phone_length": "9-11"},
    "Iran": {"phone_length": "10"},
    "Iraq": {"phone_length": "10"},
    "Ireland": {"phone_length": "9"},
    "Israel": {"phone_length": "9"},
    "Italy": {"phone_length": "9-10"},
    "Japan": {"phone_length": "10"},
    "Jordan": {"phone_length": "9"},
    "Kazakhstan": {"phone_length": "10"},
    "Kenya": {"phone_length": "9"},
    "Kuwait": {"phone_length": "8"},
    "Lebanon": {"phone_length": "8"},
    "Malaysia": {"phone_length": "9"},
    "Mexico": {"phone_length": "10"},
    "Morocco": {"phone_length": "9"},
    "Netherlands": {"phone_length": "9"},
    "New Zealand": {"phone_length": "8-10"},
    "Nigeria": {"phone_length": "10"},
    "Norway": {"phone_length": "8"},
    "Pakistan": {"phone_length": "10"},
    "Peru": {"phone_length": "9"},
    "Philippines": {"phone_length": "9-10"},
    "Poland": {"phone_length": "9"},
    "Portugal": {"phone_length": "9"},
    "Qatar": {"phone_length": "8"},
    "Romania": {"phone_length": "9"},
    "Russia": {"phone_length": "10"},
    "Saudi Arabia": {"phone_length": "9"},
    "Singapore": {"phone_length": "8"},
    "South Africa": {"phone_length": "9"},
    "South Korea": {"phone_length": "9-10"},
    "Spain": {"phone_length": "9"},
    "Sweden": {"phone_length": "7-10"},
    "Switzerland": {"phone_length": "9"},
    "Thailand": {"phone_length": "9"},
    "Turkey": {"phone_length": "10"},
    "Ukraine": {"phone_length": "9"},
    "United Arab Emirates": {"phone_length": "9"},
    "United Kingdom": {"phone_length": "9-10"},
    "United States": {"phone_length": "10"},
    "Vietnam": {"phone_length": "8"},
    "Yemen": {"phone_length": "9"}
  };

  final countryphone = countryInfoJson[countryName]?["phone_length"];

  if (countryphone != null) {
    return int.parse(countryphone);
  }

  return null;
}

String getTimeOfDay() {
  final now = DateTime.now();
  final hour = now.hour;

  if (hour >= 5 && hour < 12) {
    return 'Morning';
  } else if (hour >= 12 && hour < 17) {
    return 'Afternoon';
  } else if (hour >= 17 && hour < 21) {
    return 'Evening';
  } else {
    return 'hide'; // Or you can combine night with morning if needed.
  }
}

int? calculateTimeDifferenceInMinutes(
  DateTime inputDateTime,
  DateTime presentDate,
) {
  final Duration difference = presentDate.difference(inputDateTime);
  return difference.inMinutes;
}

int? differenceInMilliseconds(
  DateTime inputDateTime,
  DateTime presentDate,
) {
  final Duration difference = presentDate.difference(inputDateTime);
  return difference.inMilliseconds;
}

List<String> str2split(String str) {
  return str.split(' ');
}

bool? isLandscape(
  double width,
  double height,
) {
  return width > height;
}

int calculateMinutesBetweenDatetimes(
  DateTime startDatetime,
  DateTime endDatetime,
) {
  final DateTime startDatetimeNormalized =
      startDatetime.copyWith(second: 0, millisecond: 0);
  final DateTime endDatetimeNormalized =
      endDatetime.copyWith(second: 0, millisecond: 0);

  // Calculate the time difference, which returns a Duration object.
  final Duration timeDifference =
      endDatetimeNormalized.difference(startDatetimeNormalized);

  // Get the total number of full minutes from the Duration object.
  return timeDifference.inMinutes;
}

DateTime? getFeatureTimeViaAddHurMin(
  DateTime date,
  int hur,
  int min,
) {
  DateTime futureTime = date.add(Duration(hours: hur));
  futureTime = futureTime.add(Duration(minutes: min));
  return futureTime;
}

List<String> getCountryListWithTranslation(String langCode) {
  final englishCountries = [
    "Afghanistan",
    "Aland Islands",
    "Albania",
    "Algeria",
    "American Samoa",
    "Andorra",
    "Angola",
    "Anguilla",
    "Antarctica",
    "Antigua and Barbuda",
    "Argentina",
    "Armenia",
    "Aruba",
    "Australia",
    "Austria",
    "Azerbaijan",
    "Bahamas",
    "Bahrain",
    "Bangladesh",
    "Barbados",
    "Belarus",
    "Belgium",
    "Belize",
    "Benin",
    "Bermuda",
    "Bhutan",
    "Bolivia",
    "Bosnia and Herzegovina",
    "Botswana",
    "Brazil",
    "British Indian Ocean Territory",
    "Brunei Darussalam",
    "Bulgaria",
    "Burkina Faso",
    "Burundi",
    "Cambodia",
    "Cameroon",
    "Canada",
    "Cape Verde",
    "Cayman Islands",
    "Central African Republic",
    "Chad",
    "Chile",
    "China",
    "Christmas Island",
    "Cocos (Keeling) Islands",
    "Colombia",
    "Comoros",
    "Congo",
    "Congo, The Democratic Republic of the Congo",
    "Cook Islands",
    "Costa Rica",
    "Cote d'Ivoire",
    "Croatia",
    "Cuba",
    "Cyprus",
    "Czech Republic",
    "Denmark",
    "Djibouti",
    "Dominica",
    "Dominican Republic",
    "Ecuador",
    "Egypt",
    "El Salvador",
    "Equatorial Guinea",
    "Eritrea",
    "Estonia",
    "Ethiopia",
    "Falkland Islands (Malvinas)",
    "Faroe Islands",
    "Fiji",
    "Finland",
    "France",
    "French Guiana",
    "French Polynesia",
    "Gabon",
    "Gambia",
    "Georgia",
    "Germany",
    "Ghana",
    "Gibraltar",
    "Greece",
    "Greenland",
    "Grenada",
    "Guadeloupe",
    "Guam",
    "Guatemala",
    "Guernsey",
    "Guinea",
    "Guinea-Bissau",
    "Guyana",
    "Haiti",
    "Holy See (Vatican City State)",
    "Honduras",
    "Hong Kong",
    "Hungary",
    "Iceland",
    "India",
    "Indonesia",
    "Iran, Islamic Republic of Persian Gulf",
    "Iraq",
    "Ireland",
    "Isle of Man",
    "Israel",
    "Italy",
    "Jamaica",
    "Japan",
    "Jersey",
    "Jordan",
    "Kazakhstan",
    "Kenya",
    "Kiribati",
    "Korea, Democratic People's Republic of Korea",
    "Korea, Republic of South Korea",
    "Kuwait",
    "Kyrgyzstan",
    "Laos",
    "Latvia",
    "Lebanon",
    "Lesotho",
    "Liberia",
    "Libyan Arab Jamahiriya",
    "Liechtenstein",
    "Lithuania",
    "Luxembourg",
    "Macao",
    "Macedonia",
    "Madagascar",
    "Malawi",
    "Malaysia",
    "Maldives",
    "Mali",
    "Malta",
    "Marshall Islands",
    "Martinique",
    "Mauritania",
    "Mauritius",
    "Mayotte",
    "Mexico",
    "Micronesia, Federated States of Micronesia",
    "Moldova",
    "Monaco",
    "Mongolia",
    "Montenegro",
    "Montserrat",
    "Morocco",
    "Mozambique",
    "Myanmar",
    "Namibia",
    "Nauru",
    "Nepal",
    "Netherlands",
    "Netherlands Antilles",
    "New Caledonia",
    "New Zealand",
    "Nicaragua",
    "Niger",
    "Nigeria",
    "Niue",
    "Norfolk Island",
    "Northern Mariana Islands",
    "Norway",
    "Oman",
    "Pakistan",
    "Palau",
    "Palestinian Territory, Occupied",
    "Panama",
    "Papua New Guinea",
    "Paraguay",
    "Peru",
    "Philippines",
    "Pitcairn",
    "Poland",
    "Portugal",
    "Puerto Rico",
    "Qatar",
    "Romania",
    "Russia",
    "Rwanda",
    "Reunion",
    "Saint Barthelemy",
    "Saint Helena, Ascension and Tristan Da Cunha",
    "Saint Kitts and Nevis",
    "Saint Lucia",
    "Saint Martin",
    "Saint Pierre and Miquelon",
    "Saint Vincent and the Grenadines",
    "Samoa",
    "San Marino",
    "Sao Tome and Principe",
    "Saudi Arabia",
    "Senegal",
    "Serbia",
    "Seychelles",
    "Sierra Leone",
    "Singapore",
    "Slovakia",
    "Slovenia",
    "Solomon Islands",
    "Somalia",
    "South Africa",
    "South Sudan",
    "South Georgia and the South Sandwich Islands",
    "Spain",
    "Sri Lanka",
    "Sudan",
    "Suriname",
    "Svalbard and Jan Mayen",
    "Swaziland",
    "Sweden",
    "Switzerland",
    "Syrian Arab Republic",
    "Taiwan",
    "Tajikistan",
    "Tanzania, United Republic of Tanzania",
    "Thailand",
    "Timor-Leste",
    "Togo",
    "Tokelau",
    "Tonga",
    "Trinidad and Tobago",
    "Tunisia",
    "Turkey",
    "Turkmenistan",
    "Turks and Caicos Islands",
    "Tuvalu",
    "Uganda",
    "Ukraine",
    "United Arab Emirates",
    "United Kingdom",
    "United States",
    "Uruguay",
    "Uzbekistan",
    "Vanuatu",
    "Venezuela, Bolivarian Republic of Venezuela",
    "Vietnam",
    "Virgin Islands, British",
    "Virgin Islands, U.S",
    "Wallis and Futuna",
    "Yemen",
    "Zambia",
    "Zimbabwe",
  ];

  // Map of English country names to their Arabic translations.
  final Map<String, String> arabicTranslations = {
    "Afghanistan": "أفغانستان",
    "Aland Islands": "جزر آلاند",
    "Albania": "ألبانيا",
    "Algeria": "الجزائر",
    "American Samoa": "ساموا الأمريكية",
    "Andorra": "أندورا",
    "Angola": "أنجولا",
    "Anguilla": "أنجويلا",
    "Antarctica": "أنتاركتيكا",
    "Antigua and Barbuda": "أنتيغوا وبربودا",
    "Argentina": "الأرجنتين",
    "Armenia": "أرمينيا",
    "Aruba": "أروبا",
    "Australia": "أستراليا",
    "Austria": "النمسا",
    "Azerbaijan": "أذربيجان",
    "Bahamas": "جزر البهاما",
    "Bahrain": "البحرين",
    "Bangladesh": "بنغلاديش",
    "Barbados": "بربادوس",
    "Belarus": "بيلاروسيا",
    "Belgium": "بلجيكا",
    "Belize": "بليز",
    "Benin": "بنين",
    "Bermuda": "برمودا",
    "Bhutan": "بوتان",
    "Bolivia": "بوليفيا",
    "Bosnia and Herzegovina": "البوسنة والهرسك",
    "Botswana": "بوتسوانا",
    "Brazil": "البرازيل",
    "British Indian Ocean Territory": "إقليم المحيط الهندي البريطاني",
    "Brunei Darussalam": "بروناي",
    "Bulgaria": "بلغاريا",
    "Burkina Faso": "بوركينا فاسو",
    "Burundi": "بوروندي",
    "Cambodia": "كمبوديا",
    "Cameroon": "الكاميرون",
    "Canada": "كندا",
    "Cape Verde": "الرأس الأخضر",
    "Cayman Islands": "جزر كايمان",
    "Central African Republic": "جمهورية أفريقيا الوسطى",
    "Chad": "تشاد",
    "Chile": "تشيلي",
    "China": "الصين",
    "Christmas Island": "جزيرة الكريسماس",
    "Cocos (Keeling) Islands": "جزر كوكوس (كيلينغ)",
    "Colombia": "كولومبيا",
    "Comoros": "جزر القمر",
    "Congo": "الكونغو",
    "Congo, The Democratic Republic of the Congo":
        "جمهورية الكونغو الديمقراطية",
    "Cook Islands": "جزر كوك",
    "Costa Rica": "كوستاريكا",
    "Cote d'Ivoire": "ساحل العاج",
    "Croatia": "كرواتيا",
    "Cuba": "كوبا",
    "Cyprus": "قبرص",
    "Czech Republic": "جمهورية التشيك",
    "Denmark": "الدنمارك",
    "Djibouti": "جيبوتي",
    "Dominica": "دومينيكا",
    "Dominican Republic": "جمهورية الدومينيكان",
    "Ecuador": "الإكوادور",
    "Egypt": "مصر",
    "El Salvador": "السلفادور",
    "Equatorial Guinea": "غينيا الاستوائية",
    "Eritrea": "إريتريا",
    "Estonia": "إستونيا",
    "Ethiopia": "إثيوبيا",
    "Falkland Islands (Malvinas)": "جزر فوكلاند (مالفيناس)",
    "Faroe Islands": "جزر فارو",
    "Fiji": "فيجي",
    "Finland": "فنلندا",
    "France": "فرنسا",
    "French Guiana": "غويانا الفرنسية",
    "French Polynesia": "بولينيزيا الفرنسية",
    "Gabon": "الجابون",
    "Gambia": "غامبيا",
    "Georgia": "جورجيا",
    "Germany": "ألمانيا",
    "Ghana": "غانا",
    "Gibraltar": "جبل طارق",
    "Greece": "اليونان",
    "Greenland": "جرينلاند",
    "Grenada": "غرينادا",
    "Guadeloupe": "جوادلوب",
    "Guam": "جوام",
    "Guatemala": "غواتيمالا",
    "Guernsey": "غيرنسي",
    "Guinea": "غينيا",
    "Guinea-Bissau": "غينيا بيساو",
    "Guyana": "غيانا",
    "Haiti": "هايتي",
    "Holy See (Vatican City State)": "الكرسي الرسولي (دولة مدينة الفاتيكان)",
    "Honduras": "هندوراس",
    "Hong Kong": "هونغ كونغ",
    "Hungary": "المجر",
    "Iceland": "أيسلندا",
    "India": "الهند",
    "Indonesia": "إندونيسيا",
    "Iran, Islamic Republic of Persian Gulf": "إيران",
    "Iraq": "العراق",
    "Ireland": "أيرلندا",
    "Isle of Man": "جزيرة مان",
    "Israel": "إسرائيل",
    "Italy": "إيطاليا",
    "Jamaica": "جامايكا",
    "Japan": "اليابان",
    "Jersey": "جيرسي",
    "Jordan": "الأردن",
    "Kazakhstan": "كازاخستان",
    "Kenya": "كينيا",
    "Kiribati": "كيريباتي",
    "Korea, Democratic People's Republic of Korea": "كوريا الشمالية",
    "Korea, Republic of South Korea": "كوريا الجنوبية",
    "Kuwait": "الكويت",
    "Kyrgyzstan": "قيرغيزستان",
    "Laos": "لاوس",
    "Latvia": "لاتفيا",
    "Lebanon": "لبنان",
    "Lesotho": "ليسوتو",
    "Liberia": "ليبيريا",
    "Libyan Arab Jamahiriya": "الجماهيرية العربية الليبية",
    "Liechtenstein": "ليختنشتاين",
    "Lithuania": "ليتوانيا",
    "Luxembourg": "لوكسمبورغ",
    "Macao": "ماكاو",
    "Macedonia": "مقدونيا",
    "Madagascar": "مدغشقر",
    "Malawi": "مالاوي",
    "Malaysia": "ماليزيا",
    "Maldives": "جزر المالديف",
    "Mali": "مالي",
    "Malta": "مالطا",
    "Marshall Islands": "جزر مارشال",
    "Martinique": "مارتينيك",
    "Mauritania": "موريتانيا",
    "Mauritius": "موريشيوس",
    "Mayotte": "مايوت",
    "Mexico": "المكسيك",
    "Micronesia, Federated States of Micronesia": "ميكرونيزيا",
    "Moldova": "مولدوفا",
    "Monaco": "موناكو",
    "Mongolia": "منغوليا",
    "Montenegro": "الجبل الأسود",
    "Montserrat": "مونتسيرات",
    "Morocco": "المغرب",
    "Mozambique": "موزمبيق",
    "Myanmar": "ميانمار",
    "Namibia": "ناميبيا",
    "Nauru": "ناورو",
    "Nepal": "نيبال",
    "Netherlands": "هولندا",
    "Netherlands Antilles": "جزر الأنتيل الهولندية",
    "New Caledonia": "كاليدونيا الجديدة",
    "New Zealand": "نيوزيلندا",
    "Nicaragua": "نيكاراغوا",
    "Niger": "النيجر",
    "Nigeria": "نيجيريا",
    "Niue": "نيوي",
    "Norfolk Island": "جزيرة نورفولك",
    "Northern Mariana Islands": "جزر ماريانا الشمالية",
    "Norway": "النرويج",
    "Oman": "عمان",
    "Pakistan": "باكستان",
    "Palau": "بالاو",
    "Palestinian Territory, Occupied": "الأراضي الفلسطينية المحتلة",
    "Panama": "بنما",
    "Papua New Guinea": "بابوا غينيا الجديدة",
    "Paraguay": "باراغواي",
    "Peru": "بيرو",
    "Philippines": "الفلبين",
    "Pitcairn": "بيتكيرن",
    "Poland": "بولندا",
    "Portugal": "البرتغال",
    "Puerto Rico": "بورتوريكو",
    "Qatar": "قطر",
    "Romania": "رومانيا",
    "Russia": "روسيا",
    "Rwanda": "رواندا",
    "Reunion": "ريونيون",
    "Saint Barthelemy": "سان بارتيليمي",
    "Saint Helena, Ascension and Tristan Da Cunha":
        "سانت هيلينا وأسينشين وتريستان دا كونا",
    "Saint Kitts and Nevis": "سانت كيتس ونيفيس",
    "Saint Lucia": "سانت لوسيا",
    "Saint Martin": "سانت مارتن",
    "Saint Pierre and Miquelon": "سان بيير وميكلون",
    "Saint Vincent and the Grenadines": "سانت فنسنت وجزر غرينادين",
    "Samoa": "ساموا",
    "San Marino": "سان مارينو",
    "Sao Tome and Principe": "ساو تومي وبرينسيبي",
    "Saudi Arabia": "المملكة العربية السعودية",
    "Senegal": "السنغال",
    "Serbia": "صربيا",
    "Seychelles": "سيشل",
    "Sierra Leone": "سيراليون",
    "Singapore": "سنغافورة",
    "Slovakia": "سلوفاكيا",
    "Slovenia": "سلوفينيا",
    "Solomon Islands": "جزر سليمان",
    "Somalia": "الصومال",
    "South Africa": "جنوب أفريقيا",
    "South Sudan": "جنوب السودان",
    "South Georgia and the South Sandwich Islands":
        "جورجيا الجنوبية وجزر ساندويتش الجنوبية",
    "Spain": "إسبانيا",
    "Sri Lanka": "سريلانكا",
    "Sudan": "السودان",
    "Suriname": "سورينام",
    "Svalbard and Jan Mayen": "سفالبارد وجان مايان",
    "Swaziland": "سوازيلاند",
    "Sweden": "السويد",
    "Switzerland": "سويسرا",
    "Syrian Arab Republic": "الجمهورية العربية السورية",
    "Taiwan": "تايوان",
    "Tajikistan": "طاجيكستان",
    "Tanzania, United Republic of Tanzania": "تنزانيا",
    "Thailand": "تايلاند",
    "Timor-Leste": "تيمور الشرقية",
    "Togo": "توغو",
    "Tokelau": "توكيلاو",
    "Tonga": "تونغا",
    "Trinidad and Tobago": "ترينيداد وتوباغو",
    "Tunisia": "تونس",
    "Turkey": "تركيا",
    "Turkmenistan": "تركمانستان",
    "Turks and Caicos Islands": "جزر تركس وكايكوس",
    "Tuvalu": "توفالو",
    "Uganda": "أوغندا",
    "Ukraine": "أوكرانيا",
    "United Arab Emirates": "الإمارات العربية المتحدة",
    "United Kingdom": "المملكة المتحدة",
    "United States": "الولايات المتحدة",
    "Uruguay": "أوروغواي",
    "Uzbekistan": "أوزبكستان",
    "Vanuatu": "فانواتو",
    "Venezuela, Bolivarian Republic of Venezuela": "فنزويلا",
    "Vietnam": "فيتنام",
    "Virgin Islands, British": "جزر العذراء البريطانية",
    "Virgin Islands, U.S": "جزر العذراء الأمريكية",
    "Wallis and Futuna": "واليس وفوتونا",
    "Yemen": "اليمن",
    "Zambia": "زامبيا",
    "Zimbabwe": "زيمبابوي",
  };

  final List<String> displayList = [];

  // Determine if the requested language is Arabic
  final bool isArabic = langCode.toUpperCase() == 'AR';

  for (final enCountry in englishCountries) {
    if (isArabic) {
      // If Arabic is requested, use the translated name (with English fallback)
      final arCountry = arabicTranslations[enCountry] ?? enCountry;
      displayList.add(arCountry);
    } else {
      // Default to English if EN is requested or the language code is invalid/missing
      displayList.add(enCountry);
    }
  }

  return displayList;
}

String convertToEnglishNumerals(String phoneNumber) {
  if (phoneNumber == null || phoneNumber.isEmpty) {
    return '';
  }

  // Define a comprehensive map of non-Latin numerals to their English equivalents.
  final Map<String, String> numeralMap = {
    // Arabic-Indic Numerals
    '٠': '0', '١': '1', '٢': '2', '٣': '3', '٤': '4',
    '٥': '5', '٦': '6', '٧': '7', '٨': '8', '٩': '9',

    // Eastern Arabic / Persian Numerals
    '۰': '0', '۱': '1', '۲': '2', '۳': '3', '۴': '4',
    '۵': '5', '۶': '6', '۷': '7', '۸': '8', '۹': '9',

    // Devanagari Numerals (e.g., Hindi, Marathi)
    '०': '0', '१': '1', '२': '2', '३': '3', '٤': '4',
    '५': '5', '٦': '6', '७': '7', '८': '8', '९': '9',
  };

  String result = phoneNumber;

  // 1. Replace non-English numerals with their ASCII counterparts.
  numeralMap.forEach((nonEnglish, english) {
    result = result.replaceAll(nonEnglish, english);
  });

  // 2. Remove '+', '-', and spaces for a cleaner digit string.
  result = result.replaceAll('+', '').replaceAll('-', '').replaceAll(' ', '');

  return result;
}

List<TopicQuestionRecord> shuffleQuestions(
    List<TopicQuestionRecord> questionsList) {
  if (questionsList == null || questionsList.isEmpty) {
    return questionsList;
  }

  // Use the Dart shuffle method for randomization
  questionsList.shuffle();

  return questionsList;
}

bool checkStringContent(String inputString) {
  if (inputString == null) {
    return true;
  }

  // Trim the string to account for potential leading/trailing whitespace
  final cleanString = inputString.trim();

  // If the string is empty after trimming, it contains no disallowed characters (numbers).
  if (cleanString.isEmpty) {
    return true;
  }

  // Regular Expression to detect the presence of any numerical digit (0-9).
  // \d is a shorthand for [0-9].
  final numberRegex = RegExp(r'\d');

  // If the regex matches (meaning a digit is found), return false.
  // The string is considered invalid if it contains any number.
  if (numberRegex.hasMatch(cleanString)) {
    return false;
  }

  // If no digits are found, the string is valid (contains letters, punctuation, symbols, etc.).
  return true;
}
